package mtech.irs.ekgs.kie.rules.search

import mtech.irs.ekgs.model.*
import mtech.irs.ekgs.frameworx.*

rule "node scan result"
activation-group "search-result"
salience 10
when
    si : SearchInput( value != null && value.startsWith("360-degree Scan") )
    sr : SearchResults()
then
    Frameworx.searchResultForNodeScan(sr, si);
end

rule "node scan result (dialogflow)"
activation-group "search-result"
salience 10
when
    da : DialogAction ( name == "node-scan" )
    sr : SearchResults()
then
    Frameworx.searchResultForNodeScan(sr, da);
end