package mtech.irs.ekgs.kie.rules.search

import mtech.irs.ekgs.model.*
import mtech.irs.ekgs.frameworx.*

rule "node scan suggestion"
activation-group "search-suggestion"
salience 10
when
    SearchInput( value != null && value.startsWith("360-degree Scan") )
    sr : SearchResults()
then
    Frameworx.searchSuggestionForNodeScan(sr, "360-degree Scan for ");
end

rule "node scan suggestion for people"
activation-group "search-suggestion"
salience 20
when
    SearchInput( value != null && value.startsWith("360-degree Scan for People") )
    sr : SearchResults()
then
    Frameworx.searchSuggestionForNodeScan(sr, "360-degree Scan for ", "People");
end

rule "node scan suggestion for process"
activation-group "search-suggestion"
salience 20
when
    SearchInput( value != null && value.startsWith("360-degree Scan for Process") )
    sr : SearchResults()
then
    Frameworx.searchSuggestionForNodeScan(sr, "360-degree Scan for ", "Process");
end

rule "node scan suggestion for technology"
activation-group "search-suggestion"
salience 20
when
    SearchInput( value != null && value.startsWith("360-degree Scan for Technology") )
    sr : SearchResults()
then
    Frameworx.searchSuggestionForNodeScan(sr, "360-degree Scan for ", "Technology");
end
