package mtech.irs.ekgs.kie.rules.search

import mtech.irs.ekgs.model.*

rule "node scan suggestion"
activation-group "search-suggestion"
salience 10
when
    SearchInput( value.startsWith("360 degree scan") )
    sr : SearchResults()
then
    sr.addSuggestion("360 degree scan for People");
    sr.addSuggestion("360 degree scan for Process");
    sr.addSuggestion("360 degree scan for Technology");
end

rule "node scan suggestion for technology"
activation-group "search-suggestion"
salience 20
when
    SearchInput( value.startsWith("360 degree scan for Technology") )
    sr : SearchResults()
then
    sr.addSuggestion("360 degree scan for Technology Customer Order Management"); 
    sr.addSuggestion("360 degree scan for Technology Customer Order Establishment");
    sr.addSuggestion("360 degree scan for Technology Customer Order Lifecycle Management");
    sr.addSuggestion("360 degree scan for Technology Customer Order Enrichment");
end