package mtech.irs.ekgs.kie.rules.search

import mtech.irs.ekgs.model.*
import mtech.irs.ekgs.frameworx.*

rule "process stream scan suggestion"
activation-group "search-suggestion"
salience 10
when
    SearchInput( value != null && value.startsWith("End-to-End Process Scan") )
    sr : SearchResults()
then
    Frameworx.searchSuggestionForProcessStreamScan(sr, "End-to-End Process Scan for ");
end
