package mtech.irs.ekgs.kie.rules.search

import mtech.irs.ekgs.model.*
import mtech.irs.ekgs.frameworx.*

rule "relation scan result"
activation-group "search-result"
salience 10
when
    si : SearchInput( value != null && value.startsWith("Relationship Scan") )
    sr : SearchResults()
then
    Frameworx.searchResultForRelationScan(sr, si);
end

rule "relation scan result (dialogflow)"
activation-group "search-result"
salience 10
when
    da : DialogAction( name == "relationship-scan" )
    sr : SearchResults()
then
    Frameworx.searchResultForRelationScan(sr, da);
end